services:
  db:
    image: neo4j:5.12.0-community
    depends_on:
      - app
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_server_memory_heap_max__size=1.5G
      - NEO4J_server_memory_pagecache_size=1.5G
      - NEO4J_AUTH=neo4j/testtest
    deploy:
      resources:
        limits:
          memory: 3g

  app:
    image: neo4jtp:latest
    environment:
      - JSON_URL=http://160.98.47.134/dblpv13.json
      - MAX_NODES=50000
      - NEO4J_IP=db
      - NEO4J_PORT=7687
    deploy:
      resources:
        limits:
          memory: 1g
