apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-db-importer-deployment
  namespace: pet-via-adv-da-ba23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j-db-importer
  template:
    metadata:
      labels:
        app: neo4j-db-importer
    spec:
      containers:
        - name: app
          env:
            - name: JSON_URL
              value: http://160.98.47.134/dblpv13.json
            - name: MAX_NODES
              value: "50000"
            - name: NEO4J_IP
              value: db-service
            - name: NEO4J_PORT
              value: "80"
          image: ghcr.io/mse-advdaba/neo4j-db-importer:latest
          imagePullPolicy: Always
          # limit the memory usage of the app container to 4GB
          resources:
            limits:
              memory: "1Gi"
        - name: db
          env:
            - name: NEO4J_dbms_memory_heap_max__size
              value: 1.5G
            - name: NEO4J_dbms_memory_pagecache_size
              value: 1.5G
            - name: NEO4J_AUTH
              value: neo4j/testtest
          image: neo4j:5.12.0-community
          imagePullPolicy: Always
          ports:
            - containerPort: 7474
              name: http
              protocol: TCP
            - containerPort: 7687
              name: bolt
              protocol: TCP
          resources:
            limits:
              memory: "3Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-db-service
  namespace: pet-via-adv-da-ba23
spec:
  ports:
    - name: http
      port: 80
      targetPort: 7474
  selector:
    app: neo4j-db-importer
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: pet-via-adv-da-ba23
spec:
  ports:
    - name: bolt
      port: 80
      targetPort: 7687
  selector:
    app: neo4j-db-importer
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: db-ingress
  namespace: pet-via-adv-da-ba23
spec:
  rules:
    - host: neo4j-db-importer.kube.isc.heia-fr.ch
      http:
        paths:
          - backend:
              service:
                name: web-db-service
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: database-neo4j-db-importer.kube.isc.heia-fr.ch
      http:
        paths:
          - backend:
              service:
                name: db-service
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - neo4j-db-importer.kube.isc.heia-fr.ch
        - database-neo4j-db-importer.kube.isc.heia-fr.ch